server:
  port: 8089

spring:
  application:
    name: summer-trade-consumer
  main:
    allow-bean-definition-overriding: true
    web-application-type: none

dubbo:
  scan:
    base-packages: com.trade.*.*
  registry:
    address: zookeeper://localhost:2181
  metadata-report:
    address: zookeeper://localhost:2181